//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           superkdf9_simple
//      File:              superkdf9_simple_inst.v
//      Date:              星期三, 10 四月 2013 18:45:44 CST
//      Version:           2.1
//      Targeted Family:   EC
//
//   =======================================================================

superkdf9_simple superkdf9_simple_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .uartSIN(uartSIN) // 
, .uartSOUT(uartSOUT) // 
, .uartRXRDY_N(uartRXRDY_N) // 
, .uartTXRDY_N(uartTXRDY_N) // 
, .spiMISO_MASTER(spiMISO_MASTER) // 
, .spiMOSI_MASTER(spiMOSI_MASTER) // 
, .spiSS_N_MASTER(spiSS_N_MASTER) // [1-1:0]
, .spiSCLK_MASTER(spiSCLK_MASTER) // 
, .gpioPIO_BOTH_IN(gpioPIO_BOTH_IN) // [32-1:0]
, .gpioPIO_BOTH_OUT(gpioPIO_BOTH_OUT) // [32-1:0]
, .uart_debugSIN(uart_debugSIN) // 
, .uart_debugSOUT(uart_debugSOUT) // 
);
